### ISSUE TITLE
Drupal漏洞环境不完整

### ISSUE THREAD

**Issue by Yxuan18** [vulhub/vulhub#254]
Drupal最新版本中，Dockerfile文件中只有drupal，只是`docker-compose.yml`中没有加载数据库镜像，导致容器运行后无法正常安装并运行。建议增加数据库，示例在下面，可以直接更新到文件中
```
version: '2'
services:
  web:
   image: drupal:8.5.0
   ports:
     - "8080:80"
   depends_on:
     - mysql
  mysql:
   image: mysql:5.5
   environment: 
       - MYSQL_DATABASE=drupal
       - MYSQL_USER=test
       - MYSQL_PASSWORD=test
       - MYSQL_ROOT_PASSWORD=root
   restart: always
```
如果有不对的地方，请指正，谢谢
