### ISSUE TITLE
nacos derby RCE 靶机感觉有点问题

### ISSUE THREAD

**Issue by 1c3z** [vulhub/vulhub#544]
操作系统: Centos 7
Docker 版本20.10.21

https://github.com/vulhub/vulhub/tree/master/nacos/CVE-2021-29442

/nacos/v1/cs/ops/data/removal 接口上传文件一直提示

"message":"File '/tmp/file1473855XXXX.tmp' does not exist",

![image](https://github.com/user-attachments/assets/e21c39f2-914a-4bf9-8c09-e935e5ab360a)

我下了个windows 版本的正常

![image](https://github.com/user-attachments/assets/208e8d95-f49a-41e7-8960-6c458c4cb9fe)

我用官方的镜像也是报错。

```
version: "2"
services:
  nacos:
    image: nacos/nacos-server:1.4.0
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=security
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
    volumes:
      - ./standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"

```
