### ISSUE TITLE
关于Docker-compose.yml 中version配置建议

### ISSUE THREAD

**Issue by insilen** [vulhub/vulhub#545]
- Which environment: 哪个环境出现BUG [e.g. all docker-compose.yml]
 - Host OS: 操作系统 [e.g. Ubuntu]
 - OS Version: 操作系统版本 [e.g. 24.04]
 - Docker version: Docker 版本 [e.g. Docker version 27.1.2-ce, build d01f264]
 - Compose version: Docker-Compose 版本 [e.g. docker compose version 2.29.1]
 - Describe your bug:  docker compose build
 - [x] 主机是否在中国大陆
 - [x] 是否重试过仍然出现这个错误

```
docker compose build
WARN[0000] /opt/vulhub/flask/ssti/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
```

问题原因，现行 docker compose 版本已不支持 version 配置行，如：
```yaml
version: "2"
services:
 web:
   image: vulhub/flask:1.1.1
   volumes:
    - ./src:/app
   ports:
    - "8000:8000"
```
如果按照这个配置文件 则会出现报错。建议全局替换所有docker-compose.yml文件中的 `version:`行为`---`

```yaml
---
services:
 web:
   image: vulhub/flask:1.1.1
   volumes:
    - ./src:/app
   ports:
    - "8000:8000"
```
以适配新版本
